//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabrika1.proje
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FabrikaEntities : DbContext
    {
        public FabrikaEntities()
            : base("name=FabrikaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Internet_Sales> Internet_Sales { get; set; }
        public virtual DbSet<Materıals_Avaılable> Materıals_Avaılable { get; set; }
        public virtual DbSet<Shoe_Manufacturıng> Shoe_Manufacturıng { get; set; }
        public virtual DbSet<Shoes_ın_and_out> Shoes_ın_and_out { get; set; }
    }
}
