//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabrika1.proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Internet_Sales
    {
        public int ID { get; set; }
        public string Brand { get; set; }
        public string Colour { get; set; }
        public string Number { get; set; }
        public string pıece { get; set; }
        public decimal prıce { get; set; }
        public decimal barcod_no { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletdDate { get; set; }
        public bool İsdeleted { get; set; }
        public string Model { get; internal set; }
    }
}
