//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fabrika1.proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materıals_Avaılable
    {
        public int ID { get; set; }
        public string Colour { get; set; }
        public string Model { get; set; }
        public string Brand { get; set; }
        public decimal Barcod_No { get; set; }
        public string quantıty { get; set; }
        public string number_plate { get; set; }
        public string breed { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> DeletdDate { get; set; }
        public bool İsdeleted { get; set; }
    }
}
